#!/usr/bin/env npx ts-node
/**
 * AI UAT Report Generator
 * Generates HTML and Markdown reports from test results
 */

import * as fs from "fs";
import * as path from "path";

interface TestResult {
  id: string;
  question: string;
  expectedIntent: string;
  detectedIntent?: string;
  expectedLanguage: string;
  detectedLanguage?: string;
  expectedRepository?: string;
  status: "passed" | "failed" | "skipped";
  responseTime?: number;
  error?: string;
}

interface CategoryResult {
  category: string;
  total: number;
  passed: number;
  failed: number;
  passRate: number;
  tests: TestResult[];
}

interface SummaryReport {
  total: number;
  passed: number;
  failed: number;
  skipped: number;
  passRate: number;
  coverage: number;
  categories: Record<string, CategoryResult>;
  timestamp: string;
  regressions: string[];
}

function generateMarkdownReport(report: SummaryReport): string {
  let md = `# AI UAT Test Report

## Summary

| Metric | Value |
|--------|-------|
| Total Tests | ${report.total} |
| Passed | ${report.passed} (${report.passRate.toFixed(1)}%) |
| Failed | ${report.failed} |
| Skipped | ${report.skipped} |
| Coverage | ${report.coverage}% |
| Timestamp | ${report.timestamp} |

## Category Breakdown

| Category | Total | Passed | Failed | Pass Rate |
|----------|-------|--------|--------|-----------|
`;

  Object.entries(report.categories).forEach(([category, cat]) => {
    const status = cat.failed > 0 ? "❌" : "✅";
    md += `| ${status} ${category} | ${cat.total} | ${cat.passed} | ${cat.failed} | ${cat.passRate.toFixed(1)}% |\n`;
  });

  if (report.regressions.length > 0) {
    md += `
## Regressions

The following tests are failing (regressions):

`;
    report.regressions.forEach((id) => {
      const test = findTestById(report, id);
      if (test) {
        md += `- **${id}**: ${test.question}\n`;
        md += `  - Expected: ${test.expectedIntent}\n`;
        md += `  - Error: ${test.error}\n\n`;
      }
    });
  }

  md += `
## Detailed Results

### Category Details

`;

  Object.entries(report.categories).forEach(([category, cat]) => {
    md += `#### ${category}\n\n`;
    md += `| ID | Question | Expected | Status | Response Time |\n`;
    md += `|----|----------|----------|--------|---------------|\n`;
    
    cat.tests.forEach((test) => {
      const status = test.status === "passed" ? "✅" : test.status === "skipped" ? "⏭️" : "❌";
      md += `| ${test.id} | ${test.question.substring(0, 40)}... | ${test.expectedIntent} | ${status} | ${test.responseTime || "-"}ms |\n`;
    });
    
    md += "\n";
  });

  md += `
---
*Report generated by AI UAT Test Suite*
`;

  return md;
}

function generateHtmlReport(report: SummaryReport): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>AI UAT Test Report</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      max-width: 1200px;
      margin: 0 auto;
      padding: 20px;
      background: #f5f5f5;
    }
    .header {
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: white;
      padding: 30px;
      border-radius: 10px;
      margin-bottom: 20px;
    }
    .header h1 { margin: 0 0 10px 0; }
    .header p { margin: 0; opacity: 0.9; }
    .summary {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
      gap: 15px;
      margin-bottom: 20px;
    }
    .metric {
      background: white;
      padding: 20px;
      border-radius: 8px;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
      text-align: center;
    }
    .metric .value {
      font-size: 2em;
      font-weight: bold;
      color: #667eea;
    }
    .metric .label {
      color: #666;
      font-size: 0.9em;
    }
    .pass { color: #22c55e; }
    .fail { color: #ef4444; }
    .category {
      background: white;
      border-radius: 8px;
      padding: 20px;
      margin-bottom: 15px;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }
    .category-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 15px;
      padding-bottom: 10px;
      border-bottom: 1px solid #eee;
    }
    .category-title {
      font-weight: bold;
      font-size: 1.2em;
    }
    .pass-rate {
      padding: 5px 15px;
      border-radius: 20px;
      font-weight: bold;
    }
    .pass-rate.high { background: #dcfce7; color: #22c55e; }
    .pass-rate.medium { background: #fef3c7; color: #f59e0b; }
    .pass-rate.low { background: #fee2e2; color: #ef4444; }
    table {
      width: 100%;
      border-collapse: collapse;
    }
    th, td {
      padding: 10px;
      text-align: left;
      border-bottom: 1px solid #eee;
    }
    th { background: #f9fafb; font-weight: 600; }
    .status { font-weight: bold; }
    .status.passed { color: #22c55e; }
    .status.failed { color: #ef4444; }
    .status.skipped { color: #f59e0b; }
    .failed-list {
      background: #fee2e2;
      border-left: 4px solid #ef4444;
      padding: 15px;
      margin: 15px 0;
      border-radius: 0 8px 8px 0;
    }
    .failed-list h3 { margin: 0 0 10px 0; color: #ef4444; }
    .failed-item {
      background: white;
      padding: 10px;
      margin-bottom: 10px;
      border-radius: 5px;
    }
    .footer {
      text-align: center;
      color: #666;
      margin-top: 30px;
      padding-top: 20px;
      border-top: 1px solid #eee;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>🎯 AI UAT Test Report</h1>
    <p>Generated: ${new Date(report.timestamp).toLocaleString()}</p>
  </div>

  <div class="summary">
    <div class="metric">
      <div class="value">${report.total}</div>
      <div class="label">Total Tests</div>
    </div>
    <div class="metric">
      <div class="value pass">${report.passed}</div>
      <div class="label">Passed</div>
    </div>
    <div class="metric">
      <div class="value fail">${report.failed}</div>
      <div class="label">Failed</div>
    </div>
    <div class="metric">
      <div class="value">${report.passRate.toFixed(1)}%</div>
      <div class="label">Pass Rate</div>
    </div>
  </div>

  ${report.regressions.length > 0 ? `
  <div class="failed-list">
    <h3>⚠️ Regressions (${report.regressions.length} tests failing)</h3>
    ${report.regressions.map(id => {
      const test = findTestById(report, id);
      return test ? `
      <div class="failed-item">
        <strong>${id}</strong>: ${test.question}<br>
        <small>Expected: ${test.expectedIntent} | Error: ${test.error}</small>
      </div>
      ` : '';
    }).join('')}
  </div>
  ` : ''}

  <h2>Category Breakdown</h2>
  ${Object.entries(report.categories).map(([category, cat]) => {
    const passRateClass = cat.passRate >= 90 ? 'high' : cat.passRate >= 70 ? 'medium' : 'low';
    return `
    <div class="category">
      <div class="category-header">
        <span class="category-title">${category}</span>
        <span class="pass-rate ${passRateClass}">${cat.passRate.toFixed(1)}%</span>
      </div>
      <table>
        <thead>
          <tr>
            <th>ID</th>
            <th>Question</th>
            <th>Expected Intent</th>
            <th>Status</th>
            <th>Time</th>
          </tr>
        </thead>
        <tbody>
          ${cat.tests.map(test => `
          <tr>
            <td>${test.id}</td>
            <td>${test.question.substring(0, 50)}${test.question.length > 50 ? '...' : ''}</td>
            <td>${test.expectedIntent}</td>
            <td class="status ${test.status}">${test.status.toUpperCase()}</td>
            <td>${test.responseTime || '-'}ms</td>
          </tr>
          `).join('')}
        </tbody>
      </table>
    </div>
    `;
  }).join('')}

  <div class="footer">
    <p>Generated by AI UAT Test Suite | ${report.total} tests across ${Object.keys(report.categories).length} categories</p>
  </div>
</body>
</html>
`;
}

function findTestById(report: SummaryReport, id: string): TestResult | undefined {
  for (const cat of Object.values(report.categories)) {
    const test = cat.tests.find(t => t.id === id);
    if (test) return test;
  }
  return undefined;
}

function generateCoverageReport(report: SummaryReport): string {
  const categories = Object.entries(report.categories);
  const totalTests = report.total;
  
  let md = `# AI UAT Coverage Report

## Overview

This report shows the test coverage across all 15 categories.

## Coverage Matrix

| Category | Tests | Coverage |
|----------|-------|----------|
`;

  categories.forEach(([category, cat]) => {
    const coverage = ((cat.total / 20) * 100).toFixed(0);
    md += `| ${category} | ${cat.total} | ${coverage}% |\n`;
  });

  md += `
## Language Coverage

| Language | Test Count |
|----------|------------|
| English | ${categories.reduce((acc, [, cat]) => acc + cat.tests.filter(t => t.expectedLanguage === 'en').length, 0)} |
| Kannada | ${categories.reduce((acc, [, cat]) => acc + cat.tests.filter(t => t.expectedLanguage === 'kn').length, 0)} |
| Mixed | ${categories.reduce((acc, [, cat]) => acc + cat.tests.filter(t => t.expectedLanguage === 'mixed').length, 0)} |

## User Persona Coverage

| Persona | Test Count |
|---------|------------|
| New Devotee | ${categories.reduce((acc, [, cat]) => acc + cat.tests.filter(t => t.id.includes('C1-') || t.id.includes('C2-') || t.id.includes('C3-')).length, 0)} |
| Regular Devotee | ${categories.reduce((acc, [, cat]) => acc + cat.tests.filter(t => t.id.includes('C4-') || t.id.includes('C5-')).length, 0)} |
| Kannada Only | ${categories.reduce((acc, [, cat]) => acc + cat.tests.filter(t => t.id.includes('C13-')).length, 0)} |
| Mixed Language | ${categories.reduce((acc, [, cat]) => acc + cat.tests.filter(t => t.id.includes('C14-')).length, 0)} |

## Intent Coverage

Total unique intents tested: ${new Set(categories.flatMap(([, cat]) => cat.tests.map(t => t.expectedIntent))).size}

---
*Coverage report generated by AI UAT Test Suite*
`;

  return md;
}

// Main function
function main() {
  const reportsDir = path.join(__dirname, "../../reports/ai-uat");
  
  // Find the latest report
  if (!fs.existsSync(reportsDir)) {
    console.error("No reports found. Run tests first.");
    process.exit(1);
  }
  
  const files = fs.readdirSync(reportsDir)
    .filter(f => f.endsWith('.json'))
    .sort()
    .reverse();
  
  if (files.length === 0) {
    console.error("No reports found. Run tests first.");
    process.exit(1);
  }
  
  const latestReportPath = path.join(reportsDir, files[0]);
  const report: SummaryReport = JSON.parse(fs.readFileSync(latestReportPath, 'utf-8'));
  
  // Generate Markdown report
  const mdReport = generateMarkdownReport(report);
  const mdPath = path.join(reportsDir, 'uat-report.md');
  fs.writeFileSync(mdPath, mdReport);
  console.log(`Markdown report: ${mdPath}`);
  
  // Generate HTML report
  const htmlReport = generateHtmlReport(report);
  const htmlPath = path.join(reportsDir, 'uat-report.html');
  fs.writeFileSync(htmlPath, htmlReport);
  console.log(`HTML report: ${htmlPath}`);
  
  // Generate coverage report
  const coverageReport = generateCoverageReport(report);
  const coveragePath = path.join(reportsDir, 'coverage-report.md');
  fs.writeFileSync(coveragePath, coverageReport);
  console.log(`Coverage report: ${coveragePath}`);
  
  console.log('\nReports generated successfully!');
}

main();

export { generateMarkdownReport, generateHtmlReport, generateCoverageReport };
