/**
 * Types for the Aaradhane Event Generator
 * 
 * These types support reading Guru Parampara data from Firestore
 * and generating Aaradhane events automatically.
 */

import type { Timestamp } from "firebase/firestore";

export type LunarMonth =
  | "Caitra" | "Vaiśākha" | "Jyeṣṭha" | "Āṣāḍha"
  | "Śrāvaṇa" | "Bhādrapada" | "Āśvina" | "Kārttika"
  | "Mārgaśīrṣa" | "Pauṣa" | "Māgha" | "Phālguna";

export type Paksha = "Shukla" | "Krishna";

export type Tithi =
  | "Pratipada" | "Dvitiya" | "Tṛtiya" | "Chaturthi" | "Panchami"
  | "Shashti" | "Saptami" | "Ashtami" | "Navami" | "Dashami"
  | "Ekadashi" | "Dvadashi" | "Trayodashi" | "Chaturdashi" | "Purnima"
  | "Amavasya";

export type AaradhanePhase = "Poorva" | "Madhya" | "Uttara";

export type GuruImportance = "major" | "minor";

/**
 * Guru Parampara record stored in Firestore
 * Contains lunar calendar data for automatic Aaradhane event generation
 */
export interface GuruParamparaRecord {
  /** Document ID */
  id: string;
  
  /** Display name */
  guruName: string;
  
  /** Full title of the Aaradhane event */
  aaradhaneTitle: string;
  
  /** Position in guru parampara (1-17) */
  paramparaNumber: number;
  
  /** Lunar calendar data */
  lunarMonth: LunarMonth;
  paksha: Paksha;
  tithiNumber: number;
  tithi: Tithi;
  
  /** Duration in days (1-3) */
  durationDays: number;
  
  /** For Sri Raghavendra Swamy: which phase */
  raghavendraPhase?: AaradhanePhase;
  
  /** Importance level */
  importance: GuruImportance;
  
  /** Whether this Guru's Aaradhane should be generated */
  enabled: boolean;
  
  /** Optional description about significance */
  description?: string;
  
  /** Rituals performed during this Aaradhane */
  rituals?: string[];
  
  /** Offerings made during this Aaradhane */
  offerings?: string[];
  
  /** Last updated timestamp */
  updatedAt?: string;
}

/**
 * Firestore guruParampara collection structure
 */
export interface GuruParamparaCollection {
  /** Collection document ID */
  id: string;
  
  /** Heading text */
  heading?: string;
  headingKannada?: string;
  subheading?: string;
  subheadingKannada?: string;
  
  /** Individual Guru records */
  gurus: GuruParamparaRecord[];
  
  /** Metadata */
  updatedAt?: string;
}

/**
 * Generated event ready to be stored in Firestore
 */
export interface GeneratedAaradhaneEvent {
  /** Unique identifier for deduplication */
  eventKey: string;
  
  /** Event title */
  title: string;
  
  /** Event description */
  description: string;
  
  /** Guru name */
  guru: string;
  
  /** Category (always "Aaradhane") */
  category: "Aaradhane";
  
  /** Event start date (YYYY-MM-DD) */
  date: string;
  
  /** Event end date (YYYY-MM-DD) */
  endDate: string;
  
  /** All-day event */
  allDay: boolean;
  
  /** Featured event flag */
  featured: boolean;
  
  /** Published flag */
  published: boolean;
  
  /** Auto-generated flag for safety checks */
  autoGenerated: boolean;
  
  /** Year for this event */
  year: number;
  
  /** Guru parampara number */
  paramparaNumber: number;
  
  /** Lunar calendar info */
  lunarCalendar: {
    lunarMonth: string;
    paksha: string;
    tithi: string;
    tithiNumber: number;
  };
  
  /** Optional phase for Sri Raghavendra Swamy */
  raghavendraPhase?: "Poorva" | "Madhya" | "Uttara";
  
  /** Importance level */
  importance: "major" | "minor";
  
  /** Rituals performed during this Aaradhane */
  rituals?: string[];
  
  /** Offerings made during this Aaradhane */
  offerings?: string[];
  
  /** Significance of the event */
  significance?: string;
  
  /** Guru name (duplicate for compatibility) */
  guruName?: string;
}

/**
 * Result of generating events for a year
 */
export interface GenerateResult {
  /** All generated events */
  events: GeneratedAaradhaneEvent[];
  
  /** Summary statistics */
  summary: {
    total: number;
    raghavendraCount: number;
    majorCount: number;
    minorCount: number;
  };
}

/**
 * Firestore event document structure
 */
export interface FirestoreEventDocument {
  title: string;
  description: string;
  location: string;
  startDate: Timestamp;
  endDate: Timestamp;
  featured: boolean;
  published: boolean;
  status: "Upcoming" | "Ongoing" | "Completed";
  category: "Aaradhane";
  guru: string;
  guruName?: string;
  autoGenerated: boolean;
  year: number;
  paramparaNumber: number;
  raghavendraPhase?: "Poorva" | "Madhya" | "Uttara";
  lunarCalendar: {
    lunarMonth: string;
    paksha: string;
    tithi: string;
    tithiNumber: number;
  };
  rituals: string[];
  offerings: string[];
  significance: string;
  createdAt?: Date;
  updatedAt?: Date;
}

/**
 * Existing Firestore event for comparison
 */
export interface ExistingEvent {
  id: string;
  title: string;
  guru: string;
  year: number;
  autoGenerated: boolean;
  startDate: Date | null;
}

/**
 * Update result for a single event
 */
export interface EventUpdateResult {
  /** The event that was processed */
  event: GeneratedAaradhaneEvent;
  
  /** Action taken */
  action: "created" | "updated" | "skipped" | "error";
  
  /** Error message if any */
  error?: string;
  
  /** Existing event ID if updated */
  existingId?: string;
}

/**
 * Final result of the update process
 */
export interface UpdateResult {
  /** All events that were created */
  created: EventUpdateResult[];
  
  /** All events that were updated */
  updated: EventUpdateResult[];
  
  /** All events that were skipped */
  skipped: EventUpdateResult[];
  
  /** All events that had errors */
  errors: EventUpdateResult[];
  
  /** Summary of operations */
  summary: {
    created: number;
    updated: number;
    skipped: number;
    errors: number;
  };
}

/**
 * Configuration for the generator
 */
export interface GeneratorConfig {
  /** Year to generate events for */
  year: number;
  
  /** Whether to update existing events */
  updateExisting: boolean;
  
  /** Whether to publish events automatically */
  autoPublish: boolean;
  
  /** Whether to mark events as featured */
  autoFeature: boolean;
  
  /** Default location for events */
  location: string;
}
