// Intent Types for Raya AI
// These define the possible intents the chatbot can classify

export enum Intent {
  // Temple Information
  TEMPLE_TIMINGS = "TEMPLE_TIMINGS",
  CONTACT_INFORMATION = "CONTACT_INFORMATION",
  LOCATION = "LOCATION",
  ADDRESS = "ADDRESS",
  
  // Events & Festivals
  UPCOMING_EVENTS = "UPCOMING_EVENTS",
  NEXT_AARADHANE = "NEXT_AARADHANE",
  FESTIVAL_INFO = "FESTIVAL_INFO",
  
  // Sevas & Worship
  SPECIAL_SEVAS = "SPECIAL_SEVAS",
  DAILY_POOJA = "DAILY_POOJA",
  SEVA_BOOKING = "SEVA_BOOKING",
  
  // Donations & Contributions
  DONATION = "DONATION",
  DONATION_PURPOSE = "DONATION_PURPOSE",
  DONATION_80G = "DONATION_80G",
  
  // Bookings & Appointments
  BOOKING = "BOOKING",
  
  // Announcements
  ANNOUNCEMENTS = "ANNOUNCEMENTS",
  
  // Panchanga & Astrology
  PANCHANGA = "PANCHANGA",
  
  // Temple History & Philosophy
  TEMPLE_HISTORY = "TEMPLE_HISTORY",
  SRI_RAGHAVENDRA = "SRI_RAGHAVENDRA",
  MADHWA_PHILOSOPHY = "MADHWA_PHILOSOPHY",
  GURU_PARAMPARA = "GURU_PARAMPARA",
  BRINDAVANA = "BRINDAVANA",
  MANTRALAYA = "MANTRALAYA",
  
  // Visitor Information
  VISITOR_GUIDELINES = "VISITOR_GUIDELINES",
  DRESS_CODE = "DRESS_CODE",
  PHOTOGRAPHY = "PHOTOGRAPHY",
  
  // FAQ
  FAQ = "FAQ",
  
  // Actions
  TESTIMONIAL = "TESTIMONIAL",
  VOLUNTEER = "VOLUNTEER",
  CONTACT_REQUEST = "CONTACT_REQUEST",
  
  // General
  GENERAL_GREETING = "GENERAL_GREETING",
  THANKS = "THANKS",
  GOODBYE = "GOODBYE",
  
  // Out of Scope
  OUT_OF_SCOPE = "OUT_OF_SCOPE",
  
  // Unknown
  UNKNOWN = "UNKNOWN",
}

// Intent categories for grouping
export enum IntentCategory {
  TEMPLE_INFO = "temple_info",
  EVENTS = "events",
  SEVAS = "sevas",
  DONATIONS = "donations",
  BOOKINGS = "bookings",
  ANNOUNCEMENTS = "announcements",
  PANCHANGA = "panchanga",
  KNOWLEDGE = "knowledge",
  VISITOR = "visitor",
  FAQ = "faq",
  ACTIONS = "actions",
  GENERAL = "general",
  OUT_OF_SCOPE = "out_of_scope",
  UNKNOWN = "unknown",
}

// Intent priority (higher = checked first)
// More specific intents should have higher priority
export enum IntentPriority {
  GREETING = 100,
  THANKS = 95,
  GOODBYE = 90,
  OUT_OF_SCOPE = 80,
  // Temple Info
  ADDRESS = 85,
  LOCATION = 84,
  CONTACT_INFORMATION = 75, // Lower - generic "how" can match this
  TEMPLE_TIMINGS = 70,
  // Events
  NEXT_AARADHANE = 67,
  UPCOMING_EVENTS = 66,
  // Sevas
  SEVA_BOOKING = 64,
  DAILY_POOJA = 63, // Higher than TEMPLE_TIMINGS - "pooja" is specific
  SPECIAL_SEVAS = 62,
  // Donations
  DONATION_80G = 58,
  DONATION_PURPOSE = 57,
  DONATION = 56, // Higher than CONTACT - "donate" is specific
  // Knowledge
  PANCHANGA = 50,
  ANNOUNCEMENTS = 49,
  TEMPLE_HISTORY = 45,
  SRI_RAGHAVENDRA = 44,
  MADHWA_PHILOSOPHY = 43,
  GURU_PARAMPARA = 42,
  BRINDAVANA = 41,
  MANTRALAYA = 40,
  // Visitor
  PHOTOGRAPHY = 35,
  DRESS_CODE = 34,
  VISITOR_GUIDELINES = 33,
  // General
  FAQ = 20,
  CONTACT_REQUEST = 15,
  VOLUNTEER = 14,
  TESTIMONIAL = 13,
  FESTIVAL_INFO = 12,
  BOOKING = 11,
  UNKNOWN = 10,
}

// Retrieval type for hybrid responses
export enum RetrievalType {
  REPOSITORY = "repository",     // Data from Firebase repositories
  KNOWLEDGE_BASE = "knowledge_base", // Static knowledge articles
  KEYWORD_MATCH = "keyword_match", // Exact keyword matching
  SEMANTIC_MATCH = "semantic_match", // Semantic similarity matching
  HYBRID_MATCH = "hybrid_match",   // Combined keyword + semantic
  LLM = "llm",                   // Generated by LLM
  FALLBACK = "fallback",         // Default response
  MIXED = "mixed",               // Combination of sources
}

// Detection result
export interface IntentDetectionResult {
  intent: Intent;
  category: IntentCategory;
  confidence: number; // 0-100
  source: RetrievalType;
  matchedKeywords: string[];
  requiresStructuredData: boolean;
  fallbackIntent?: Intent; // Suggested fallback if primary fails
}

// Keyword patterns for intent detection
export interface IntentPattern {
  intent: Intent;
  category: IntentCategory;
  priority: IntentPriority;
  keywords: {
    en: string[];
    kn?: string[]; // Kannada keywords
  };
  patterns?: RegExp[];
  requiresStructuredData: boolean;
}
