// Intent Types for Raya AI
// These define the possible intents the chatbot can classify

export enum Intent {
  // Temple Information
  TEMPLE_TIMINGS = "TEMPLE_TIMINGS",
  CONTACT_INFORMATION = "CONTACT_INFORMATION",
  LOCATION = "LOCATION",
  ADDRESS = "ADDRESS",
  OFFICE_HOURS = "OFFICE_HOURS",
  
  // Events & Festivals
  UPCOMING_EVENTS = "UPCOMING_EVENTS",
  NEXT_AARADHANE = "NEXT_AARADHANE",
  FESTIVAL_INFO = "FESTIVAL_INFO",
  
  // Devotional Content
  DAILY_QUOTE = "DAILY_QUOTE",
  
  // Sevas & Worship
  SPECIAL_SEVAS = "SPECIAL_SEVAS",
  DAILY_POOJA = "DAILY_POOJA",
  SEVA_BOOKING = "SEVA_BOOKING",
  ANNADANA = "ANNADANA",
  PRASADA = "PRASADA",
  
  // Donations & Contributions
  DONATION = "DONATION",
  DONATION_PURPOSE = "DONATION_PURPOSE",
  DONATION_80G = "DONATION_80G",
  
  // Bookings & Appointments
  BOOKING = "BOOKING",
  
  // Announcements
  ANNOUNCEMENTS = "ANNOUNCEMENTS",
  
  // Panchanga & Astrology
  PANCHANGA = "PANCHANGA",
  
  // Temple History & Philosophy
  TEMPLE_HISTORY = "TEMPLE_HISTORY",
  SRI_RAGHAVENDRA = "SRI_RAGHAVENDRA",
  MADHWA_PHILOSOPHY = "MADHWA_PHILOSOPHY",
  GURU_PARAMPARA = "GURU_PARAMPARA",
  BRINDAVANA = "BRINDAVANA",
  MANTRALAYA = "MANTRALAYA",
  
  // Visitor Information
  VISITOR_GUIDELINES = "VISITOR_GUIDELINES",
  DRESS_CODE = "DRESS_CODE",
  PHOTOGRAPHY = "PHOTOGRAPHY",
  PARKING = "PARKING",
  GALLERY = "GALLERY",
  
  // Website Navigation
  SHARE_EXPERIENCE = "SHARE_EXPERIENCE",
  COMMITTEE = "COMMITTEE",
  
  // FAQ
  FAQ = "FAQ",
  
  // Actions
  TESTIMONIAL = "TESTIMONIAL",
  VOLUNTEER = "VOLUNTEER",
  CONTACT_REQUEST = "CONTACT_REQUEST",
  
  // General
  GENERAL_GREETING = "GENERAL_GREETING",
  THANKS = "THANKS",
  GOODBYE = "GOODBYE",
  
  // Out of Scope
  OUT_OF_SCOPE = "OUT_OF_SCOPE",
  
  // Unknown
  UNKNOWN = "UNKNOWN",
}

// Intent categories for grouping
export enum IntentCategory {
  TEMPLE_INFO = "temple_info",
  EVENTS = "events",
  DEVOTIONAL = "devotional",
  SEVAS = "sevas",
  DONATIONS = "donations",
  BOOKINGS = "bookings",
  ANNOUNCEMENTS = "announcements",
  PANCHANGA = "panchanga",
  KNOWLEDGE = "knowledge",
  VISITOR = "visitor",
  FAQ = "faq",
  ACTIONS = "actions",
  GENERAL = "general",
  WEBSITE_NAVIGATION = "website_navigation",
  OUT_OF_SCOPE = "out_of_scope",
  UNKNOWN = "unknown",
}

// Intent priority (higher = checked first)
// More specific intents should have higher priority
export enum IntentPriority {
  GREETING = 100,
  THANKS = 95,
  GOODBYE = 90,
  OUT_OF_SCOPE = 80,
  // General (generic questions - high priority to catch ambiguous queries)
  FAQ = 75, // Catch generic "what", "why", "how" questions
  // Temple Info
  ADDRESS = 85,
  LOCATION = 84,
  CONTACT_INFORMATION = 65, // Lower - generic words can match this
  TEMPLE_TIMINGS = 70,
  OFFICE_HOURS = 68, // Specific temple office timing
  // Events
  NEXT_AARADHANE = 67,
  UPCOMING_EVENTS = 66,
  // Devotional Content
  DAILY_QUOTE = 69, // High priority - specific quote requests
  // Sevas
  SEVA_BOOKING = 64,
  DAILY_POOJA = 63, // Higher than TEMPLE_TIMINGS - "pooja" is specific
  SPECIAL_SEVAS = 62,
  ANNADANA = 61, // Annadana/free meal service
  PRASADA = 60, // Prasada distribution
  // Donations
  DONATION_80G = 58,
  DONATION_PURPOSE = 57,
  DONATION = 56, // Higher than CONTACT - "donate" is specific
  // Knowledge
  PANCHANGA = 75, // Higher priority - specific panchanga/tithi requests
  ANNOUNCEMENTS = 49,
  TEMPLE_HISTORY = 45,
  SRI_RAGHAVENDRA = 44,
  MADHWA_PHILOSOPHY = 43,
  GURU_PARAMPARA = 42,
  BRINDAVANA = 41,
  MANTRALAYA = 40,
  // Visitor
  GALLERY = 36,
  PHOTOGRAPHY = 35,
  DRESS_CODE = 34,
  VISITOR_GUIDELINES = 33,
  PARKING = 32,
  // Website Navigation
  SHARE_EXPERIENCE = 30, // Share testimonial/experience
  COMMITTEE = 28, // Trust committee information
  // General (continued)
  CONTACT_REQUEST = 15,
  VOLUNTEER = 14,
  TESTIMONIAL = 13,
  FESTIVAL_INFO = 12,
  BOOKING = 11,
  UNKNOWN = 10,
}

// Retrieval type for hybrid responses
export enum RetrievalType {
  REPOSITORY = "repository",     // Data from Firebase repositories
  KNOWLEDGE_BASE = "knowledge_base", // Static knowledge articles
  KEYWORD_MATCH = "keyword_match", // Exact keyword matching
  SEMANTIC_MATCH = "semantic_match", // Semantic similarity matching
  HYBRID_MATCH = "hybrid_match",   // Combined keyword + semantic
  LLM = "llm",                   // Generated by LLM
  FALLBACK = "fallback",         // Default response
  MIXED = "mixed",               // Combination of sources
  LEARNED = "learned",           // From ML learned corrections
}

// Detection result
export interface IntentDetectionResult {
  intent: Intent;
  category: IntentCategory;
  confidence: number; // 0-100
  source: RetrievalType;
  matchedKeywords: string[];
  requiresStructuredData: boolean;
  fallbackIntent?: Intent; // Suggested fallback if primary fails
}

// Keyword patterns for intent detection
export interface IntentPattern {
  intent: Intent;
  category: IntentCategory;
  priority: IntentPriority;
  keywords: {
    en: string[];
    kn?: string[]; // Kannada keywords
  };
  patterns?: RegExp[];
  requiresStructuredData: boolean;
}

/**
 * Navigation Intent Metadata
 * Contains route and button information for website navigation intents
 */
export interface NavigationIntentMetadata {
  route: string;
  buttonText: {
    en: string;
    kn?: string;
  };
  knowledgeCategory?: string;
  description: {
    en: string;
    kn?: string;
  };
}

/**
 * Map of intents that require navigation action buttons
 */
export const NAVIGATION_INTENTS: Partial<Record<Intent, NavigationIntentMetadata>> = {
  [Intent.SHARE_EXPERIENCE]: {
    route: "/testimonials",
    buttonText: {
      en: "Share Your Experience",
      kn: "ನಿಮ್ಮ ಅನುಭವ ಹಂಚಿಕೊಳ್ಳಿ",
    },
    knowledgeCategory: "testimonials",
    description: {
      en: "Share your spiritual experience at the temple with other devotees.",
      kn: "ಇತರ ಭಕ್ತರೊಂದಿಗೆ ದೇವಸ್ಥಾನದಲ್ಲಿನ ನಿಮ್ಮ ಆಧ್ಯಾತ್ಮಿಕ ಅನುಭವವನ್ನು ಹಂಚಿಕೊಳ್ಳಿ.",
    },
  },
  [Intent.PARKING]: {
    route: "/visit",
    buttonText: {
      en: "View Parking Info",
      kn: "ಪಾರ್ಕಿಂಗ್ ಮಾಹಿತಿ",
    },
    knowledgeCategory: "parking",
    description: {
      en: "Find information about temple parking facilities.",
      kn: "ದೇವಸ್ಥಾನದ ಪಾರ್ಕಿಂಗ್ ಸೌಲಭ್ಯಗಳ ಬಗ್ಗೆ ಮಾಹಿತಿ ಪಡೆಯಿರಿ.",
    },
  },
  [Intent.GALLERY]: {
    route: "/gallery",
    buttonText: {
      en: "View Gallery",
      kn: "ಗ್ಯಾಲರಿ ನೋಡಿ",
    },
    knowledgeCategory: "gallery",
    description: {
      en: "Browse photos and images from the temple.",
      kn: "ದೇವಸ್ಥಾನದ ಫೋಟೊಗಳು ಮತ್ತು ಚಿತ್ರಗಳನ್ನು ನೋಡಿ.",
    },
  },
  [Intent.PHOTOGRAPHY]: {
    route: "/guidelines",
    buttonText: {
      en: "Photography Guidelines",
      kn: "ಛಾಯಾಗ್ರಹಣ ಮಾರ್ಗಸೂಚನೆಗಳು",
    },
    knowledgeCategory: "photography",
    description: {
      en: "Learn about the photography and videography rules at the temple.",
      kn: "ದೇವಸ್ಥಾನದಲ್ಲಿ ಛಾಯಾಗ್ರಹಣ ಮತ್ತು ವೀಡಿಯೊಗ್ರಫಿ ನಿಯಮಗಳ ಬಗ್ಗೆ ತಿಳಿಯಿರಿ.",
    },
  },
  [Intent.DRESS_CODE]: {
    route: "/guidelines",
    buttonText: {
      en: "View Dress Code",
      kn: "ಉಡುಗೆ ನಿಯಮ ನೋಡಿ",
    },
    knowledgeCategory: "dress_code",
    description: {
      en: "Know the appropriate dress code for temple visits.",
      kn: "ದೇವಸ್ಥಾನ ಭೇಟಿಗೆ ಸೂಕ್ತ ಉಡುಗೆ ನಿಯಮವನ್ನು ತಿಳಿಯಿರಿ.",
    },
  },
  [Intent.ANNADANA]: {
    route: "/annadana",
    buttonText: {
      en: "Annadana (Free Meals)",
      kn: "ಅನ್ನದಾನ (ಉಚಿತ ಊಟ)",
    },
    knowledgeCategory: "annadana",
    description: {
      en: "Learn about the free meal service (Annadana) at the temple.",
      kn: "ದೇವಸ್ಥಾನದಲ್ಲಿನ ಉಚಿತ ಊಟ ಸೇವೆ (ಅನ್ನದಾನ) ಬಗ್ಗೆ ತಿಳಿಯಿರಿ.",
    },
  },
  [Intent.PRASADA]: {
    route: "/prasada",
    buttonText: {
      en: "Prasada Information",
      kn: "ಪ್ರಸಾದ ಮಾಹಿತಿ",
    },
    knowledgeCategory: "prasada",
    description: {
      en: "Information about prasada (sacred food) distribution.",
      kn: "ಪ್ರಸಾದ (ಪವಿತ್ರ ಆಹಾರ) ವಿತರಣೆಯ ಬಗ್ಗೆ ಮಾಹಿತಿ.",
    },
  },
  [Intent.COMMITTEE]: {
    route: "/trust-committee",
    buttonText: {
      en: "Trust Committee",
      kn: "ಟ್ರಸ್ಟ್ ಸಮಿತಿ",
    },
    knowledgeCategory: "committee",
    description: {
      en: "Meet the trust committee members and their roles.",
      kn: "ಟ್ರಸ್ಟ್ ಸಮಿತಿ ಸದಸ್ಯರನ್ನು ಭೇಟಿಯಾಗಿ ಮತ್ತು ಅವರ ಪಾತ್ರಗಳನ್ನು ತಿಳಿಯಿರಿ.",
    },
  },
  [Intent.OFFICE_HOURS]: {
    route: "/contact",
    buttonText: {
      en: "Office Hours",
      kn: "ಕಛೇರಿ ಸಮಯ",
    },
    knowledgeCategory: "office_hours",
    description: {
      en: "Temple office hours and administrative contact information.",
      kn: "ದೇವಸ್ಥಾನ ಕಛೇರಿ ಸಮಯ ಮತ್ತು ಆಡಳಿತ ಸಂಪರ್ಕ ಮಾಹಿತಿ.",
    },
  },
};
