/**
 * Unit tests for the Aaradhane Generator
 */

import {
  validateGeneratedEvents,
  printGenerateSummary,
  eventToFirestoreDocument,
} from "@/lib/aaradhane/generator";
import { DailyPanchanga, YearlyPanchanga } from "@/lib/aaradhane/panchanga";
import { GeneratedAaradhaneEvent } from "@/types/aaradhane-generator";

// Mock Firebase for testing
jest.mock("@/lib/firebase", () => ({
  db: null,
}));

// Mock the Firestore source module to return test data
jest.mock("@/lib/aaradhane/firestore-source", () => ({
  getGuruParamparaRecords: jest.fn().mockResolvedValue([]),
  hasGuruParamparaData: jest.fn().mockResolvedValue(false),
}));

describe("Aaradhane Generator", () => {
  describe("validateGeneratedEvents", () => {
    it("should detect missing Sri Raghavendra events", () => {
      // Create a result without Raghavendra events using mock data
      const mockResult = {
        events: [
          {
            eventKey: "madhvacharya-2026",
            title: "Sri Madhvacharya Aaradhane",
            description: "",
            guru: "Sri Madhvacharya",
            category: "Aaradhane" as const,
            date: "2026-01-01",
            endDate: "2026-01-01",
            allDay: true,
            featured: false,
            published: true,
            autoGenerated: true,
            year: 2026,
            paramparaNumber: 1,
            lunarCalendar: {
              lunarMonth: "Chaitra",
              paksha: "Shukla",
              tithi: "Pratipada",
              tithiNumber: 1,
            },
            raghavendraPhase: undefined,
            importance: "major" as const,
          },
        ],
        summary: {
          total: 1,
          raghavendraCount: 0,
          majorCount: 1,
          minorCount: 0,
        },
      };
      
      const validation = validateGeneratedEvents(mockResult, 2026);
      
      expect(validation.valid).toBe(false);
      expect(validation.errors.some(e => e.includes("Raghavendra"))).toBe(true);
    });

    it("should detect missing phases for Raghavendra", () => {
      // Create a result with only Poorva
      const mockResult = {
        events: [
          {
            eventKey: "raghavendra-poorva-2026",
            title: "Sri Raghavendra Swamy Poorva Aaradhane",
            description: "",
            guru: "Sri Raghavendra Swamy",
            category: "Aaradhane" as const,
            date: "2026-05-31",
            endDate: "2026-06-02",
            allDay: true,
            featured: false,
            published: true,
            autoGenerated: true,
            year: 2026,
            paramparaNumber: 17,
            lunarCalendar: {
              lunarMonth: "Vaishakha",
              paksha: "Krishna",
              tithi: "Trayodashi",
              tithiNumber: 13,
            },
            raghavendraPhase: "Poorva" as const,
            importance: "major" as const,
          },
        ],
        summary: {
          total: 1,
          raghavendraCount: 1,
          majorCount: 1,
          minorCount: 0,
        },
      };
      
      const validation = validateGeneratedEvents(mockResult, 2026);
      
      expect(validation.valid).toBe(false);
      expect(validation.errors).toContain("Missing Madhya Aaradhane for Sri Raghavendra Swamy");
      expect(validation.errors).toContain("Missing Uttara Aaradhane for Sri Raghavendra Swamy");
    });

    it("should detect duplicate event keys", () => {
      const mockResult = {
        events: [
          {
            eventKey: "duplicate-key",
            title: "Event 1",
            description: "",
            guru: "Guru 1",
            category: "Aaradhane" as const,
            date: "2026-01-01",
            endDate: "2026-01-01",
            allDay: true,
            featured: false,
            published: true,
            autoGenerated: true,
            year: 2026,
            paramparaNumber: 1,
            lunarCalendar: {
              lunarMonth: "Chaitra",
              paksha: "Shukla",
              tithi: "Pratipada",
              tithiNumber: 1,
            },
            importance: "major" as const,
          },
          {
            eventKey: "duplicate-key", // Same key!
            title: "Event 2",
            description: "",
            guru: "Guru 2",
            category: "Aaradhane" as const,
            date: "2026-01-02",
            endDate: "2026-01-02",
            allDay: true,
            featured: false,
            published: true,
            autoGenerated: true,
            year: 2026,
            paramparaNumber: 2,
            lunarCalendar: {
              lunarMonth: "Chaitra",
              paksha: "Shukla",
              tithi: "Pratipada",
              tithiNumber: 1,
            },
            importance: "minor" as const,
          },
        ],
        summary: {
          total: 2,
          raghavendraCount: 0,
          majorCount: 1,
          minorCount: 1,
        },
      };
      
      const validation = validateGeneratedEvents(mockResult, 2026);
      
      expect(validation.valid).toBe(false);
      expect(validation.errors).toContain("Duplicate event keys found");
    });
  });

  describe("eventToFirestoreDocument", () => {
    it("should convert event to Firestore document format", () => {
      const mockEvent = {
        eventKey: "raghavendra-poorva-2026",
        title: "Sri Raghavendra Swamy Poorva Aaradhane",
        description: "Test description",
        guru: "Sri Raghavendra Swamy",
        category: "Aaradhane" as const,
        date: "2026-05-31",
        endDate: "2026-06-02",
        allDay: true,
        featured: true,
        published: true,
        autoGenerated: true,
        year: 2026,
        paramparaNumber: 17,
        lunarCalendar: {
          lunarMonth: "Vaishakha",
          paksha: "Krishna",
          tithi: "Trayodashi",
          tithiNumber: 13,
        },
        raghavendraPhase: "Poorva" as const,
        importance: "major" as const,
      };
      
      const doc = eventToFirestoreDocument(mockEvent);
      
      expect(doc.title).toBe(mockEvent.title);
      expect(doc.description).toBe(mockEvent.description);
      expect(doc.category).toBe("Aaradhane");
      expect(doc.guru).toBe(mockEvent.guru);
      expect(doc.autoGenerated).toBe(true);
      expect(doc.year).toBe(2026);
      expect(doc.raghavendraPhase).toBe("Poorva");
      expect(doc.lunarCalendar).toEqual(mockEvent.lunarCalendar);
    });
  });

  describe("printGenerateSummary", () => {
    it("should not throw when printing summary", () => {
      const mockResult = {
        events: [
          {
            eventKey: "test-2026",
            title: "Test Event",
            description: "",
            guru: "Test Guru",
            category: "Aaradhane" as const,
            date: "2026-01-01",
            endDate: "2026-01-01",
            allDay: true,
            featured: false,
            published: true,
            autoGenerated: true,
            year: 2026,
            paramparaNumber: 1,
            lunarCalendar: {
              lunarMonth: "Chaitra",
              paksha: "Shukla",
              tithi: "Pratipada",
              tithiNumber: 1,
            },
            importance: "major" as const,
          },
        ],
        summary: {
          total: 1,
          raghavendraCount: 0,
          majorCount: 1,
          minorCount: 0,
        },
      };
      
      expect(() => printGenerateSummary(mockResult, 2026)).not.toThrow();
    });
  });
});
