/**
 * Firestore Admin SDK operations for Aaradhane events
 * 
 * Uses Firebase Admin SDK for server-side operations.
 * This is used by scripts and server actions to write to Firestore
 * with elevated permissions.
 */

import { getAdminFirestore } from "@/lib/admin-firebase";
import {
  GeneratedAaradhaneEvent,
  EventUpdateResult,
  UpdateResult,
  ExistingEvent,
} from "@/types/aaradhane-generator";
import { eventToFirestoreDocument } from "./generator";
import { Timestamp, FieldValue } from "firebase-admin/firestore";

const COLLECTION_NAME = "events";

/**
 * Query existing auto-generated events for a specific year
 */
export async function getExistingAutoGeneratedEventsAdmin(
  year: number
): Promise<ExistingEvent[]> {
  const db = await getAdminFirestore();
  
  try {
    const eventsRef = db.collection(COLLECTION_NAME);
    
    // Query for events that are auto-generated and match the year
    const snapshot = await eventsRef
      .where("autoGenerated", "==", true)
      .where("year", "==", year)
      .where("category", "==", "Aaradhane")
      .get();
    
    return snapshot.docs.map((d) => {
      const data = d.data();
      let startDate: Date | null = null;
      
      if (data.startDate) {
        if (data.startDate instanceof Timestamp) {
          startDate = data.startDate.toDate();
        } else if (typeof data.startDate.toDate === "function") {
          startDate = data.startDate.toDate();
        } else if (data.startDate.seconds) {
          startDate = new Date(data.startDate.seconds * 1000);
        }
      }
      
      return {
        id: d.id,
        title: data.title || "",
        guru: data.guru || "",
        year: data.year || year,
        autoGenerated: data.autoGenerated || false,
        startDate,
      };
    });
  } catch (error) {
    console.warn("Query with filters failed, falling back to full scan:", error);
    return getExistingAutoGeneratedEventsFallbackAdmin(year);
  }
}

/**
 * Fallback method to get existing events by fetching all and filtering
 */
async function getExistingAutoGeneratedEventsFallbackAdmin(
  year: number
): Promise<ExistingEvent[]> {
  const db = await getAdminFirestore();
  
  const eventsRef = db.collection(COLLECTION_NAME);
  const snapshot = await eventsRef.get();
  
  return snapshot.docs
    .map((d: any) => {
      const data = d.data();
      let startDate: Date | null = null;
      
      if (data.startDate) {
        if (data.startDate.toDate && typeof data.startDate.toDate === "function") {
          startDate = data.startDate.toDate();
        } else if (data.startDate.seconds) {
          startDate = new Date(data.startDate.seconds * 1000);
        }
      }
      
      return {
        id: d.id,
        title: data.title || "",
        guru: data.guru || "",
        year: data.year || year,
        autoGenerated: data.autoGenerated || false,
        startDate,
      };
    })
    .filter((event: ExistingEvent) => event.autoGenerated && event.year === year);
}

/**
 * Create or update events in Firestore using Admin SDK
 */
export async function updateFirestoreWithAdmin(
  generatedEvents: GeneratedAaradhaneEvent[],
  year: number,
  updateExisting: boolean = true
): Promise<UpdateResult> {
  const db = await getAdminFirestore();
  
  const result: UpdateResult = {
    created: [],
    updated: [],
    skipped: [],
    errors: [],
    summary: {
      created: 0,
      updated: 0,
      skipped: 0,
      errors: 0,
    },
  };
  
  // Get existing events for this year
  let existingEvents: Map<string, ExistingEvent> = new Map();
  
  if (updateExisting) {
    const existing = await getExistingAutoGeneratedEventsAdmin(year);
    existingEvents = new Map(
      existing.map((e) => [e.id, e])
    );
  }
  
  // Process each generated event
  for (const event of generatedEvents) {
    const updateResult = await processEventAdmin(
      event,
      existingEvents,
      updateExisting,
      FieldValue
    );
    
    // Categorize result
    switch (updateResult.action) {
      case "created":
        result.created.push(updateResult);
        result.summary.created++;
        break;
      case "updated":
        result.updated.push(updateResult);
        result.summary.updated++;
        break;
      case "skipped":
        result.skipped.push(updateResult);
        result.summary.skipped++;
        break;
      case "error":
        result.errors.push(updateResult);
        result.summary.errors++;
        break;
    }
  }
  
  return result;
}

/**
 * Process a single event - create, update, or skip
 */
async function processEventAdmin(
  event: GeneratedAaradhaneEvent,
  existingEvents: Map<string, ExistingEvent>,
  updateExisting: boolean,
  FieldValue: any
): Promise<EventUpdateResult> {
  const db = await getAdminFirestore();
  
  try {
    // Find existing event by matching guru name and year
    let existingId: string | null = null;
    
    if (updateExisting) {
      for (const [id, existing] of existingEvents) {
        // Match by guru name and year
        if (
          existing.guru === event.guru &&
          existing.year === event.year &&
          existing.autoGenerated
        ) {
          // For Raghavendra, also check phase
          if (
            event.guru === "Sri Raghavendra Swamy" &&
            event.raghavendraPhase
          ) {
            const existingPhase = (existing as unknown as Record<string, unknown>).raghavendraPhase;
            if (existingPhase !== event.raghavendraPhase) {
              continue;
            }
          }
          
          existingId = id;
          break;
        }
      }
    }
    
    // Build Firestore document
    const firestoreDoc = eventToFirestoreDocument(event);
    
    if (existingId) {
      // Update existing event
      const docRef = db.collection(COLLECTION_NAME).doc(existingId);
      const updateData = {
        ...firestoreDoc,
        updatedAt: FieldValue?.serverTimestamp ? FieldValue.serverTimestamp() : new Date(),
      };
      await docRef.update(updateData);
      
      return {
        event,
        action: "updated",
        existingId,
      };
    } else {
      // Create new event
      const docRef = db.collection(COLLECTION_NAME).doc();
      const setData = {
        ...firestoreDoc,
        createdAt: FieldValue?.serverTimestamp ? FieldValue.serverTimestamp() : new Date(),
        updatedAt: FieldValue?.serverTimestamp ? FieldValue.serverTimestamp() : new Date(),
      };
      await docRef.set(setData);
      
      return {
        event,
        action: "created",
        existingId: docRef.id,
      };
    }
  } catch (error) {
    console.error(`Error processing event ${event.title}:`, error);
    return {
      event,
      action: "error",
      error: error instanceof Error ? error.message : String(error),
    };
  }
}

/**
 * Print update result summary
 */
export function printUpdateSummary(result: UpdateResult): void {
  console.log("\n" + "=".repeat(60));
  console.log("FIRESTORE UPDATE SUMMARY");
  console.log("=".repeat(60));
  console.log(`\nTotal Events Processed: ${result.summary.created + result.summary.updated + result.summary.skipped + result.summary.errors}`);
  console.log(`  Created: ${result.summary.created}`);
  console.log(`  Updated: ${result.summary.updated}`);
  console.log(`  Skipped: ${result.summary.skipped}`);
  console.log(`  Errors: ${result.summary.errors}`);
  
  if (result.created.length > 0) {
    console.log("\n" + "-".repeat(60));
    console.log("Created Events:");
    console.log("-".repeat(60));
    for (const r of result.created) {
      console.log(`  ✓ ${r.event.title}`);
      console.log(`    ID: ${r.existingId}`);
      console.log(`    Date: ${r.event.date}`);
    }
  }
  
  if (result.updated.length > 0) {
    console.log("\n" + "-".repeat(60));
    console.log("Updated Events:");
    console.log("-".repeat(60));
    for (const r of result.updated) {
      console.log(`  ↻ ${r.event.title}`);
      console.log(`    ID: ${r.existingId}`);
      console.log(`    Date: ${r.event.date}`);
    }
  }
  
  if (result.errors.length > 0) {
    console.log("\n" + "-".repeat(60));
    console.log("Errors:");
    console.log("-".repeat(60));
    for (const r of result.errors) {
      console.log(`  ✗ ${r.event.title}`);
      console.log(`    Error: ${r.error}`);
    }
  }
  
  console.log("\n" + "=".repeat(60));
}
