/**
 * Firestore operations for Aaradhane events
 * 
 * Handles creating, updating, and querying Aaradhane events in Firestore.
 * Implements idempotent operations to prevent duplicate events.
 */

import {
  collection,
  doc,
  getDocs,
  addDoc,
  updateDoc,
  query,
  where,
  Timestamp,
  writeBatch,
} from "firebase/firestore";
import { db } from "@/lib/firebase";
import {
  GeneratedAaradhaneEvent,
  EventUpdateResult,
  UpdateResult,
  ExistingEvent,
} from "@/types/aaradhane-generator";
import { eventToFirestoreDocument } from "./generator";

const COLLECTION_NAME = "events";

/**
 * Query existing auto-generated events for a specific year
 */
export async function getExistingAutoGeneratedEvents(
  year: number
): Promise<ExistingEvent[]> {
  if (!db) {
    throw new Error("Firebase not configured");
  }
  
  try {
    const eventsRef = collection(db, COLLECTION_NAME);
    
    // Query for events that are auto-generated and match the year
    // We need to check both autoGenerated flag and year field
    const q = query(
      eventsRef,
      where("autoGenerated", "==", true),
      where("year", "==", year),
      where("category", "==", "Aaradhane")
    );
    
    const snapshot = await getDocs(q);
    
    return snapshot.docs.map((d) => {
      const data = d.data();
      let startDate: Date | null = null;
      
      if (data.startDate) {
        if (data.startDate instanceof Timestamp) {
          startDate = data.startDate.toDate();
        } else if (data.startDate.toDate && typeof data.startDate.toDate === "function") {
          startDate = data.startDate.toDate();
        } else if (data.startDate.seconds) {
          startDate = new Date(data.startDate.seconds * 1000);
        }
      }
      
      return {
        id: d.id,
        title: data.title || "",
        guru: data.guru || "",
        year: data.year || year,
        autoGenerated: data.autoGenerated || false,
        startDate,
      };
    });
  } catch (error) {
    // If the query fails due to missing index, fall back to fetching all and filtering
    console.warn("Query with filters failed, falling back to full scan:", error);
    return getExistingAutoGeneratedEventsFallback(year);
  }
}

/**
 * Fallback method to get existing events by fetching all and filtering
 */
async function getExistingAutoGeneratedEventsFallback(
  year: number
): Promise<ExistingEvent[]> {
  if (!db) {
    throw new Error("Firebase not configured");
  }
  
  const eventsRef = collection(db, COLLECTION_NAME);
  const snapshot = await getDocs(eventsRef);
  
  return snapshot.docs
    .map((d) => {
      const data = d.data();
      let startDate: Date | null = null;
      
      if (data.startDate) {
        if (data.startDate instanceof Timestamp) {
          startDate = data.startDate.toDate();
        } else if (data.startDate.toDate && typeof data.startDate.toDate === "function") {
          startDate = data.startDate.toDate();
        } else if (data.startDate.seconds) {
          startDate = new Date(data.startDate.seconds * 1000);
        }
      }
      
      return {
        id: d.id,
        title: data.title || "",
        guru: data.guru || "",
        year: data.year || year,
        autoGenerated: data.autoGenerated || false,
        startDate,
      };
    })
    .filter((event) => event.autoGenerated && event.year === year);
}

/**
 * Find existing event by event key (guru id + year)
 */
export async function findEventByKey(
  eventKey: string
): Promise<{ id: string; data: Record<string, unknown> } | null> {
  if (!db) {
    throw new Error("Firebase not configured");
  }
  
  const [guruId, yearStr] = eventKey.split("-");
  const year = parseInt(yearStr, 10);
  
  try {
    // Try querying by event key components
    const eventsRef = collection(db, COLLECTION_NAME);
    const q = query(
      eventsRef,
      where("autoGenerated", "==", true),
      where("year", "==", year)
    );
    
    const snapshot = await getDocs(q);
    
    // Find matching event by checking title contains guruId
    for (const docSnap of snapshot.docs) {
      const data = docSnap.data();
      const title = (data.title || "").toLowerCase();
      const id = guruId.toLowerCase();
      
      if (title.includes(id) || id.includes(title.split(" ")[0].toLowerCase())) {
        return { id: docSnap.id, data };
      }
    }
    
    return null;
  } catch (error) {
    console.error("Error finding event by key:", error);
    return null;
  }
}

/**
 * Create or update events in Firestore
 */
export async function updateFirestoreEvents(
  generatedEvents: GeneratedAaradhaneEvent[],
  year: number,
  updateExisting: boolean = true
): Promise<UpdateResult> {
  if (!db) {
    throw new Error("Firebase not configured");
  }
  
  const result: UpdateResult = {
    created: [],
    updated: [],
    skipped: [],
    errors: [],
    summary: {
      created: 0,
      updated: 0,
      skipped: 0,
      errors: 0,
    },
  };
  
  // Get existing events for this year
  let existingEvents: Map<string, ExistingEvent> = new Map();
  
  if (updateExisting) {
    const existing = await getExistingAutoGeneratedEvents(year);
    existingEvents = new Map(
      existing.map((e) => [e.id, e])
    );
  }
  
  // Process each generated event
  for (const event of generatedEvents) {
    const updateResult = await processEvent(
      event,
      existingEvents,
      updateExisting
    );
    
    // Categorize result
    switch (updateResult.action) {
      case "created":
        result.created.push(updateResult);
        result.summary.created++;
        break;
      case "updated":
        result.updated.push(updateResult);
        result.summary.updated++;
        break;
      case "skipped":
        result.skipped.push(updateResult);
        result.summary.skipped++;
        break;
      case "error":
        result.errors.push(updateResult);
        result.summary.errors++;
        break;
    }
  }
  
  return result;
}

/**
 * Process a single event - create, update, or skip
 */
async function processEvent(
  event: GeneratedAaradhaneEvent,
  existingEvents: Map<string, ExistingEvent>,
  updateExisting: boolean
): Promise<EventUpdateResult> {
  if (!db) {
    return {
      event,
      action: "error",
      error: "Firebase not configured",
    };
  }
  
  try {
    // Find existing event by matching guru name and year
    let existingId: string | null = null;
    
    if (updateExisting) {
      for (const [id, existing] of existingEvents) {
        // Match by guru name and year
        if (
          existing.guru === event.guru &&
          existing.year === event.year &&
          existing.autoGenerated
        ) {
          // For Raghavendra, also check phase
          if (
            event.guru === "Sri Raghavendra Swamy" &&
            event.raghavendraPhase
          ) {
            const existingPhase = (existing as unknown as Record<string, unknown>).raghavendraPhase;
            if (existingPhase !== event.raghavendraPhase) {
              continue;
            }
          }
          
          existingId = id;
          break;
        }
      }
    }
    
    // Build Firestore document
    const firestoreDoc = eventToFirestoreDocument(event);
    
    if (existingId) {
      // Update existing event
      const docRef = doc(db, COLLECTION_NAME, existingId);
      await updateDoc(docRef, {
        ...firestoreDoc,
        updatedAt: Timestamp.now(),
      });
      
      return {
        event,
        action: "updated",
        existingId,
      };
    } else {
      // Create new event
      const docRef = await addDoc(collection(db, COLLECTION_NAME), {
        ...firestoreDoc,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
      });
      
      return {
        event,
        action: "created",
        existingId: docRef.id,
      };
    }
  } catch (error) {
    console.error(`Error processing event ${event.title}:`, error);
    return {
      event,
      action: "error",
      error: error instanceof Error ? error.message : String(error),
    };
  }
}

/**
 * Print update result summary
 */
export function printUpdateSummary(result: UpdateResult): void {
  console.log("\n" + "=".repeat(60));
  console.log("FIRESTORE UPDATE SUMMARY");
  console.log("=".repeat(60));
  console.log(`\nTotal Events Processed: ${result.summary.created + result.summary.updated + result.summary.skipped + result.summary.errors}`);
  console.log(`  Created: ${result.summary.created}`);
  console.log(`  Updated: ${result.summary.updated}`);
  console.log(`  Skipped: ${result.summary.skipped}`);
  console.log(`  Errors: ${result.summary.errors}`);
  
  if (result.created.length > 0) {
    console.log("\n" + "-".repeat(60));
    console.log("Created Events:");
    console.log("-".repeat(60));
    for (const r of result.created) {
      console.log(`  ✓ ${r.event.title}`);
      console.log(`    ID: ${r.existingId}`);
      console.log(`    Date: ${r.event.date}`);
    }
  }
  
  if (result.updated.length > 0) {
    console.log("\n" + "-".repeat(60));
    console.log("Updated Events:");
    console.log("-".repeat(60));
    for (const r of result.updated) {
      console.log(`  ↻ ${r.event.title}`);
      console.log(`    ID: ${r.existingId}`);
      console.log(`    Date: ${r.event.date}`);
    }
  }
  
  if (result.errors.length > 0) {
    console.log("\n" + "-".repeat(60));
    console.log("Errors:");
    console.log("-".repeat(60));
    for (const r of result.errors) {
      console.log(`  ✗ ${r.event.title}`);
      console.log(`    Error: ${r.error}`);
    }
  }
  
  console.log("\n" + "=".repeat(60));
}

/**
 * Batch update events for efficiency
 * Use this when updating many events at once
 */
export async function batchUpdateFirestoreEvents(
  generatedEvents: GeneratedAaradhaneEvent[],
  year: number,
  updateExisting: boolean = true
): Promise<UpdateResult> {
  if (!db) {
    throw new Error("Firebase not configured");
  }
  
  const result: UpdateResult = {
    created: [],
    updated: [],
    skipped: [],
    errors: [],
    summary: {
      created: 0,
      updated: 0,
      skipped: 0,
      errors: 0,
    },
  };
  
  // Get existing events
  let existingEvents: Map<string, ExistingEvent> = new Map();
  
  if (updateExisting) {
    const existing = await getExistingAutoGeneratedEvents(year);
    existingEvents = new Map(existing.map((e) => [e.id, e]));
  }
  
  // Use batch write for efficiency
  const batch = writeBatch(db);
  let batchCount = 0;
  const BATCH_SIZE = 500; // Firestore limit
  
  for (const event of generatedEvents) {
    try {
      // Find existing event
      let existingId: string | null = null;
      
      if (updateExisting) {
        for (const [id, existing] of existingEvents) {
          if (
            existing.guru === event.guru &&
            existing.year === event.year &&
            existing.autoGenerated
          ) {
            if (
              event.guru === "Sri Raghavendra Swamy" &&
              event.raghavendraPhase
            ) {
              const existingPhase = (existing as unknown as Record<string, unknown>).raghavendraPhase;
              if (existingPhase !== event.raghavendraPhase) {
                continue;
              }
            }
            existingId = id;
            break;
          }
        }
      }
      
      const firestoreDoc = eventToFirestoreDocument(event);
      const now = Timestamp.now();
      
      if (existingId) {
        // Update in batch
        const docRef = doc(db, COLLECTION_NAME, existingId);
        batch.update(docRef, {
          ...firestoreDoc,
          updatedAt: now,
        });
        
        result.updated.push({
          event,
          action: "updated",
          existingId,
        });
        result.summary.updated++;
      } else {
        // Create in batch
        const docRef = doc(collection(db, COLLECTION_NAME));
        batch.set(docRef, {
          ...firestoreDoc,
          createdAt: now,
          updatedAt: now,
        });
        
        result.created.push({
          event,
          action: "created",
          existingId: docRef.id,
        });
        result.summary.created++;
      }
      
      batchCount++;
      
      // Commit batch if it reaches the limit
      if (batchCount >= BATCH_SIZE) {
        await batch.commit();
        batchCount = 0;
      }
    } catch (error) {
      result.errors.push({
        event,
        action: "error",
        error: error instanceof Error ? error.message : String(error),
      });
      result.summary.errors++;
    }
  }
  
  // Commit remaining batch
  if (batchCount > 0) {
    await batch.commit();
  }
  
  return result;
}
