/**
 * Local Aaradhane Event Generator
 * 
 * This module provides functions for generating Aaradhane events
 * WITHOUT requiring Firebase/Firestore dependencies.
 * Use this for local development, testing, and CI/CD environments.
 */

import {
  loadYearlyPanchanga,
  findDatesForLunarDate,
  getDateRangeString,
  YearlyPanchanga,
} from "./panchanga";
import {
  GeneratedAaradhaneEvent,
  GenerateResult,
  GuruParamparaRecord,
} from "@/types/aaradhane-generator";

/**
 * Generate events from a list of Guru records
 * This function works without any Firestore dependencies
 */
export function generateEventsFromGurus(
  guruRecords: GuruParamparaRecord[],
  yearlyPanchanga: YearlyPanchanga,
  year: number
): GenerateResult {
  // Filter enabled Gurus
  const enabledGurus = guruRecords.filter(g => g.enabled);
  
  if (enabledGurus.length === 0) {
    throw new Error(
      "No enabled Guru records found. " +
      "Please check the input data."
    );
  }
  
  // Generate events for each Guru
  const events: GeneratedAaradhaneEvent[] = [];
  let raghavendraCount = 0;
  let majorCount = 0;
  let minorCount = 0;
  
  for (const guru of enabledGurus) {
    const generatedEvent = generateSingleEvent(guru, yearlyPanchanga, year);
    
    if (generatedEvent) {
      events.push(generatedEvent);
      
      if (guru.guruName === "Sri Raghavendra Swamy") {
        raghavendraCount++;
      }
      if (guru.importance === "major") {
        majorCount++;
      } else {
        minorCount++;
      }
    }
  }
  
  return {
    events,
    summary: {
      total: events.length,
      raghavendraCount,
      majorCount,
      minorCount,
    },
  };
}

/**
 * Generate a single Aaradhane event
 */
function generateSingleEvent(
  guru: GuruParamparaRecord,
  yearlyPanchanga: YearlyPanchanga,
  year: number
): GeneratedAaradhaneEvent | null {
  // Find the Gregorian dates for this lunar calendar date
  const dates = findDatesForLunarDate(
    yearlyPanchanga,
    guru.lunarMonth,
    guru.paksha,
    guru.tithiNumber,
    guru.durationDays
  );
  
  // If no date found, skip this Guru for this year
  if (dates.length === 0) {
    console.warn(
      `Warning: Could not find matching date for ${guru.guruName} ` +
      `(${guru.lunarMonth} ${guru.paksha} ${guru.tithi}) in year ${year}`
    );
    return null;
  }
  
  const startDate = dates[0];
  const endDate = dates[dates.length - 1];
  
  // Generate unique event key for deduplication
  const eventKey = `${guru.id}-${year}`;
  
  return {
    eventKey,
    title: guru.aaradhaneTitle,
    description: guru.description || `${guru.guruName} Aaradhane celebration at Sri Raghavendra Swamy Matha.`,
    guru: guru.guruName,
    category: "Aaradhane",
    date: startDate,
    endDate: endDate,
    allDay: true,
    featured: false,
    published: true,
    autoGenerated: true,
    year,
    paramparaNumber: guru.paramparaNumber,
    raghavendraPhase: guru.raghavendraPhase,
    lunarCalendar: {
      lunarMonth: guru.lunarMonth,
      paksha: guru.paksha,
      tithi: guru.tithi,
      tithiNumber: guru.tithiNumber,
    },
    importance: guru.importance,
  };
}

/**
 * Print generation summary to console
 */
export function printGenerateSummary(result: GenerateResult, year: number): void {
  console.log(`
AARADHANE EVENTS GENERATION SUMMARY - ${year}
${"=".repeat(60)}
  
Total Events Generated: ${result.summary.total}

  Major Importance: ${result.summary.majorCount}
  Minor Importance: ${result.summary.minorCount}
  Sri Raghavendra Swamy: ${result.summary.raghavendraCount} events

Major Events:`);
  
  for (const event of result.events.filter(e => e.importance === "major")) {
    console.log(`  - ${event.title}`);
    console.log(`    Date: ${event.date} - ${event.endDate}`);
    console.log(`    Lunar: ${event.lunarCalendar.lunarMonth} ${event.lunarCalendar.paksha} ${event.lunarCalendar.tithi}`);
    console.log();
  }
  
  console.log(`
Minor Events:`);
  
  for (const event of result.events.filter(e => e.importance === "minor")) {
    console.log(`  - ${event.title}`);
    console.log(`    Date: ${event.date}`);
  }
  
  console.log(`
${"=".repeat(60)}
`);
}

/**
 * Validate generated events
 */
export function validateGeneratedEvents(result: GenerateResult, year: number): {
  valid: boolean;
  errors: string[];
} {
  const errors: string[] = [];
  
  // Check for Sri Raghavendra Swamy events
  const raghavendraEvents = result.events.filter(e => e.guru === "Sri Raghavendra Swamy");
  
  if (raghavendraEvents.length > 0 && raghavendraEvents.length < 3) {
    const phases = raghavendraEvents.map(e => e.raghavendraPhase);
    
    if (!phases.includes("Poorva")) {
      errors.push("Missing Poorva Aaradhane for Sri Raghavendra Swamy");
    }
    if (!phases.includes("Madhya")) {
      errors.push("Missing Madhya Aaradhane for Sri Raghavendra Swamy");
    }
    if (!phases.includes("Uttara")) {
      errors.push("Missing Uttara Aaradhane for Sri Raghavendra Swamy");
    }
  }
  
  // Check for duplicate event keys
  const eventKeys = result.events.map(e => e.eventKey);
  const uniqueKeys = new Set(eventKeys);
  
  if (eventKeys.length !== uniqueKeys.size) {
    errors.push("Duplicate event keys found");
  }
  
  // Check year matches
  for (const event of result.events) {
    if (event.year !== year) {
      errors.push(`Event ${event.eventKey} has year ${event.year}, expected ${year}`);
    }
  }
  
  return {
    valid: errors.length === 0,
    errors,
  };
}
