#!/usr/bin/env npx tsx
/**
 * Export Aaradhane Events to JSON
 * 
 * Generates events and exports them as JSON for manual import to Firestore.
 */

import * as fs from "fs";
import * as path from "path";

process.env.TZ = "Asia/Kolkata";

async function main() {
  const args = process.argv.slice(2);
  let year = new Date().getFullYear() + 1;
  
  // Parse year argument
  const yearIndex = args.indexOf("--year");
  if (yearIndex !== -1 && args[yearIndex + 1]) {
    year = parseInt(args[yearIndex + 1], 10);
  }
  
  console.log(`\nExporting Aaradhane events for ${year}...\n`);
  
  // Load modules
  const { loadYearlyPanchanga } = await import("../lib/aaradhane/panchanga");
  const { GURU_AARADHANES } = await import("../data/aaradhane/gurus");
  const { generateEventsFromGurus } = await import("../lib/aaradhane/local-generator");
  
  // Transform local data
  const transformedGurus = GURU_AARADHANES.map(g => ({
    id: g.id,
    guruName: g.guruName,
    aaradhaneTitle: g.title,
    paramparaNumber: g.paramparaNumber,
    lunarMonth: g.lunarMonth,
    paksha: g.paksha,
    tithiNumber: g.tithiNumber,
    tithi: g.tithi,
    durationDays: g.durationDays,
    raghavendraPhase: g.raghavendraPhase,
    importance: g.importance,
    enabled: true,
    description: g.description,
  }));
  
  // Load Panchanga
  const yearlyPanchanga = loadYearlyPanchanga(year);
  
  // Generate events
  const result = generateEventsFromGurus(transformedGurus, yearlyPanchanga, year);
  
  // Convert to Firestore-compatible format
  const events = result.events.map(event => {
    const startDate = new Date(event.date);
    const endDate = new Date(event.endDate);
    
    return {
      eventKey: event.eventKey,
      title: event.title,
      description: event.description,
      guru: event.guru,
      category: event.category,
      startDate: startDate.toISOString(),
      endDate: endDate.toISOString(),
      allDay: event.allDay,
      featured: event.featured,
      published: event.published,
      autoGenerated: event.autoGenerated,
      year: event.year,
      paramparaNumber: event.paramparaNumber,
      raghavendraPhase: event.raghavendraPhase,
      lunarCalendar: event.lunarCalendar,
      importance: event.importance,
    };
  });
  
  // Create output directory
  const outputDir = path.join(process.cwd(), "data", "exports");
  fs.mkdirSync(outputDir, { recursive: true });
  
  // Write JSON file
  const outputFile = path.join(outputDir, `aaradhane-events-${year}.json`);
  fs.writeFileSync(outputFile, JSON.stringify(events, null, 2));
  
  console.log(`✓ Exported ${events.length} events to ${outputFile}`);
  console.log(`\nMajor Events: ${result.summary.majorCount}`);
  console.log(`Minor Events: ${result.summary.minorCount}`);
  console.log(`Sri Raghavendra Swamy: ${result.summary.raghavendraCount} events\n`);
  
  console.log("To import to Firestore:");
  console.log("1. Go to Firebase Console > Firestore > Import JSON");
  console.log(`2. Upload ${outputFile}`);
}

main().catch(console.error);
