#!/usr/bin/env npx tsx
/**
 * Calendar Events Generator Script
 * 
 * Generates all Guru Aaradhane events for the calendar year based on Hindu Panchanga
 * and uploads them to the 'events' collection in Firestore using Firebase Admin SDK.
 * 
 * Note: This seeds the 'events' collection for the calendar, NOT the 'aaradhane' collection
 * which is used by the admin portal for Aaradhane management.
 */

import adminModule from "firebase-admin";
import { Firestore } from "firebase-admin/firestore";

import * as fs from "fs";
import * as path from "path";
import { GURU_AARADHANES } from "../data/aaradhane/gurus";

const admin = adminModule.default || adminModule;

// Create a Firestore instance
let firestoreDb: Firestore | null = null;
async function getDb() {
  if (!firestoreDb) {
    // Read service account for Firestore
    const serviceAccountPath = path.join(process.cwd(), "service-account.json");
    const serviceAccount = JSON.parse(fs.readFileSync(serviceAccountPath, "utf8"));
    
    // Create Firestore with credentials
    firestoreDb = new Firestore({
      projectId: serviceAccount.project_id,
      clientOptions: {
        credentials: {
          client_email: serviceAccount.client_email,
          private_key: serviceAccount.private_key.replace(/\\n/g, "\n"),
        },
      },
    });
  }
  return firestoreDb;
}

// Set timezone for consistent date handling
process.env.TZ = "Asia/Kolkata";

const PROJECT_ID = "sri-raghavendra-mutt";
const COLLECTION_NAME = "events";
const TARGET_YEAR = 2027;

// Initialize Firebase Admin SDK
function initializeFirebase(): any {
  // Check if already initialized
  const existingApps = admin.getApps();
  if (existingApps.length > 0) {
    return existingApps[0]!;
  }

  // Read the service account file
  const serviceAccountPath = path.join(process.cwd(), "service-account.json");
  
  if (!fs.existsSync(serviceAccountPath)) {
    throw new Error(`Service account file not found: ${serviceAccountPath}`);
  }
  
  const serviceAccount = JSON.parse(fs.readFileSync(serviceAccountPath, "utf8"));
  
  console.log("Initializing Firebase Admin SDK...");
  console.log("Project ID:", serviceAccount.project_id);
  
  return admin.initializeApp({
    credential: admin.cert(serviceAccount),
    projectId: serviceAccount.project_id,
  });
}

// Load Panchanga data for a year
function loadPanchangaData(year: number): Map<string, any> {
  const panchangaDir = path.join(process.cwd(), "data", "panchanga", String(year));
  
  if (!fs.existsSync(panchangaDir)) {
    throw new Error(`Panchanga data not found for year ${year}`);
  }
  
  const files = fs.readdirSync(panchangaDir).filter(f => f.endsWith(".json"));
  const panchangaData = new Map();
  
  for (const file of files) {
    const date = file.replace(".json", "");
    const data = JSON.parse(fs.readFileSync(path.join(panchangaDir, file), "utf8"));
    panchangaData.set(date, data);
  }
  
  return panchangaData;
}

// Generate events from gurus and panchanga data
function generateEvents(gurus: typeof GURU_AARADHANES, panchangaData: Map<string, any>, year: number): any[] {
  const events: any[] = [];
  
  for (const guru of gurus) {
    // Skip disabled gurus
    if ((guru as any).enabled === false) continue;
    
    // Find matching panchanga entry for the guru's tithi
    for (const [date, panchanga] of panchangaData) {
      const [yearStr, month, day] = date.split("-");
      
      if (parseInt(yearStr) !== year) continue;
      
      // Check if this date matches the guru's lunar calendar
      // Panchanga uses: tithi.name, tithi.paksha, masa.name
      const pakshaFromPanchanga = panchanga.tithi?.paksha || panchanga.masa?.paksha;
      const matchesPaksha = pakshaFromPanchanga === guru.paksha;
      const matchesTithi = panchanga.tithi?.name === guru.tithi || panchanga.tithi?.number === guru.tithiNumber;
      const matchesMonth = panchanga.masa?.name === guru.lunarMonth;
      
      if (matchesPaksha && matchesTithi && matchesMonth) {
        const startDate = new Date(`${year}-${month}-${day}`);
        const durationDays = guru.durationDays || 1;
        const endDate = new Date(startDate);
        endDate.setDate(endDate.getDate() + durationDays - 1);
        
        const event = {
          title: guru.title || `${guru.guruName} Aaradhane`,
          guru: guru.guruName,
          startDate: Firestore.Timestamp.fromDate(startDate),
          endDate: Firestore.Timestamp.fromDate(endDate),
          year: year,
          category: "Aaradhane",
          autoGenerated: true,
          importance: guru.importance,
          description: guru.description || "",
          tithi: guru.tithi,
          lunarMonth: guru.lunarMonth,
          paksha: guru.paksha,
          raghavendraPhase: (guru as any).raghavendraPhase,
          published: true,
        };
        
        events.push(event);
        console.log(`  ✓ Found: ${event.title} on ${date}`);
        break; // Move to next guru after finding first match
      }
    }
  }
  
  return events;
}

// Get existing events for the year
async function getExistingEvents(database: any, year: number): Promise<any[]> {
  try {
    const snapshot = await database.collection(COLLECTION_NAME)
      .where("autoGenerated", "==", true)
      .where("year", "==", year)
      .where("category", "==", "Aaradhane")
      .get();
    
    return snapshot.docs.map((d: any) => ({
      id: d.id,
      guru: d.data().guru,
      year: d.data().year,
      raghavendraPhase: d.data().raghavendraPhase,
    }));
  } catch (error) {
    console.warn("Query failed, using fallback:", (error as Error).message);
    // Fallback: fetch all and filter
    const snapshot = await database.collection(COLLECTION_NAME).get();
    return snapshot.docs
      .map((d: any) => d.data())
      .filter((d: any) => d.autoGenerated && d.year === year && d.category === "Aaradhane")
      .map((d: any) => ({ id: d.id, guru: d.guru, year: d.year, raghavendraPhase: d.raghavendraPhase }));
  }
}

// Upload events to Firestore or export to JSON
async function uploadEvents(events: any[], year: number): Promise<{ created: number; updated: number; errors: number; exported: boolean }> {
  // Try Firestore first
  try {
    const database = getDb();
    
    // Get existing events
    const existingEvents = await getExistingEvents(database, year);
    const existingMap = new Map(existingEvents.map(e => {
      const key = `${e.guru}-${e.year}-${e.raghavendraPhase || ""}`;
      return [key, e];
    }));
    
    const result = {
      created: 0,
      updated: 0,
      errors: 0,
      exported: false,
    };
    
    for (const event of events) {
      try {
        const key = `${event.guru}-${event.year}-${event.raghavendraPhase || ""}`;
        const existing = existingMap.get(key);
        
        if (existing) {
          // Update existing event
          await database.collection(COLLECTION_NAME).doc(existing.id).update({
            ...event,
            updatedAt: Firestore.FieldValue.serverTimestamp(),
          });
          result.updated++;
          console.log(`  ↻ Updated: ${event.title}`);
        } else {
          // Create new event
          await database.collection(COLLECTION_NAME).add({
            ...event,
            createdAt: Firestore.FieldValue.serverTimestamp(),
            updatedAt: Firestore.FieldValue.serverTimestamp(),
          });
          result.created++;
          console.log(`  ✓ Created: ${event.title}`);
        }
      } catch (error) {
        result.errors++;
        console.error(`  ✗ Error: ${event.title} - ${(error as Error).message}`);
      }
    }
    
    return result;
  } catch (firestoreError) {
    // If Firestore fails, export to JSON file
    console.log("\n⚠️ Firestore upload failed, exporting to JSON file instead...");
    console.log("You can import this file using Firebase CLI or Console.\n");
    
    // Convert Firestore timestamps to ISO strings for JSON
    const exportData = events.map(event => {
      const exportEvent: any = { ...event };
      if (event.startDate && event.startDate.toDate) {
        exportEvent.startDate = event.startDate.toDate().toISOString();
      }
      if (event.endDate && event.endDate.toDate) {
        exportEvent.endDate = event.endDate.toDate().toISOString();
      }
      return exportEvent;
    });
    
    // Create exports directory if it doesn't exist
    const exportsDir = path.join(process.cwd(), "data", "exports");
    if (!fs.existsSync(exportsDir)) {
      fs.mkdirSync(exportsDir, { recursive: true });
    }
    
    // Write to JSON file
    const exportPath = path.join(exportsDir, `aaradhane-events-${year}.json`);
    fs.writeFileSync(exportPath, JSON.stringify(exportData, null, 2));
    
    console.log(`✓ Events exported to: ${exportPath}`);
    console.log(`  Total events: ${exportData.length}`);
    console.log("\n  To import to Firestore:");
    console.log(`  1. Go to Firebase Console > Firestore > Start collection`);
    console.log(`  2. Import the events from ${exportPath}`);
    console.log(`  3. Or use: firebase firestore:import ${exportPath}`);
    
    return {
      created: events.length,
      updated: 0,
      errors: 0,
      exported: true,
    };
  }
}

// Main function
async function main() {
  console.log("\n" + "=".repeat(60));
  console.log("CALENDAR EVENTS GENERATOR - " + TARGET_YEAR);
  console.log("=".repeat(60));
  console.log("\nTimezone: Asia/Kolkata");
  
  try {
    // Initialize Firebase
    initializeFirebase();
    console.log("Firebase Admin SDK initialized successfully\n");
    
    // Load data
    console.log("Loading Panchanga data for 2027...");
    const panchangaData = loadPanchangaData(TARGET_YEAR);
    console.log(`Loaded ${panchangaData.size} days of Panchanga data\n`);
    
    console.log("Loading Guru data...");
    const gurus = GURU_AARADHANES;
    console.log(`Loaded ${gurus.length} Guru records\n`);
    
    // Generate events
    console.log("-".repeat(60));
    console.log("GENERATING EVENTS FOR 2027");
    console.log("-".repeat(60));
    
    const events = generateEvents(gurus, panchangaData, TARGET_YEAR);
    
    console.log("\n" + "=".repeat(60));
    console.log("EVENTS SUMMARY");
    console.log("=".repeat(60));
    console.log(`Total events generated: ${events.length}`);
    
    // Separate major and minor events
    const majorEvents = events.filter((e: any) => e.importance === "major");
    const minorEvents = events.filter((e: any) => e.importance === "minor");
    
    console.log(`  Major importance: ${majorEvents.length}`);
    console.log(`  Minor importance: ${minorEvents.length}`);
    
    // Count Raghavendra phases
    const raghavendraPhases = events.filter((e: any) => e.guru === "Sri Raghavendra Swamy");
    console.log(`  Sri Raghavendra Swamy: ${raghavendraPhases.length} events\n`);
    
    // Upload to Firestore
    console.log("-".repeat(60));
    console.log("UPLOADING TO FIRESTORE");
    console.log("-".repeat(60));
    
    const uploadResult = await uploadEvents(events, TARGET_YEAR);
    
    console.log("\n" + "=".repeat(60));
    console.log("GENERATION COMPLETE");
    console.log("=".repeat(60));
    console.log(`Created: ${uploadResult.created}`);
    console.log(`Updated: ${uploadResult.updated}`);
    console.log(`Errors: ${uploadResult.errors}`);
    
    process.exit(uploadResult.errors > 0 ? 1 : 0);
    
  } catch (error) {
    console.error("\n❌ Error:", (error as Error).message);
    console.error((error as Error).stack);
    process.exit(1);
  }
}

main();
