#!/usr/bin/env npx tsx
/**
 * Import Aaradhane Events to Firestore via REST API
 * 
 * This script uses the Firestore REST API to import events.
 * Note: Requires Firebase Admin SDK or authenticated user.
 */

import * as fs from "fs";
import * as path from "path";

process.env.TZ = "Asia/Kolkata";

interface EventData {
  eventKey: string;
  title: string;
  description: string;
  guru: string;
  category: string;
  startDate: string;
  endDate: string;
  allDay: boolean;
  featured: boolean;
  published: boolean;
  autoGenerated: boolean;
  year: number;
  paramparaNumber: number;
  raghavendraPhase?: string;
  lunarCalendar: {
    lunarMonth: string;
    paksha: string;
    tithi: string;
    tithiNumber: number;
  };
  importance: string;
}

async function importEvents(year: number): Promise<void> {
  const exportFile = path.join(process.cwd(), "data", "exports", `aaradhane-events-${year}.json`);
  
  if (!fs.existsSync(exportFile)) {
    console.error(`❌ Export file not found: ${exportFile}`);
    console.log(`\nRun: npm run export:aaradhane -- --year ${year}`);
    return;
  }

  const events: EventData[] = JSON.parse(fs.readFileSync(exportFile, "utf-8"));
  
  console.log(`\n===========================================`);
  console.log(`IMPORTING AARADHANE EVENTS FOR ${year}`);
  console.log(`===========================================\n`);
  console.log(`Events to import: ${events.length}`);
  console.log(`Source file: ${exportFile}\n`);

  // Display events
  console.log("EVENTS:");
  events.forEach((event, i) => {
    const startDate = new Date(event.startDate).toLocaleDateString("en-IN", {
      timeZone: "Asia/Kolkata",
    });
    const endDate = new Date(event.endDate).toLocaleDateString("en-IN", {
      timeZone: "Asia/Kolkata",
    });
    const dateRange = startDate === endDate ? startDate : `${startDate} - ${endDate}`;
    console.log(`  ${i + 1}. ${event.title}`);
    console.log(`     Date: ${dateRange}`);
    console.log(`     Importance: ${event.importance}`);
    console.log();
  });

  console.log("\n" + "=".repeat(50));
  console.log("MANUAL IMPORT REQUIRED");
  console.log("=".repeat(50));
  console.log("\nTo import these events to Firestore:");
  console.log("\n1. Go to Firebase Console:");
  console.log("   https://console.firebase.google.com");
  console.log("\n2. Select project: sri-raghavendra-mutt");
  console.log("\n3. Go to Firestore Database > Data tab");
  console.log("\n4. Click 'Start collection' and enter: aaradhanes");
  console.log("\n5. For each event, click 'Add document' with:");
  console.log("   - Document ID: (leave auto-generated)");
  console.log("   - Fields from the JSON file\n");

  // Also try Firebase CLI if available
  console.log("\nAlternatively, using Firebase CLI:");
  console.log(`  npx firebase firestore:import data/exports/aaradhane-events-${year}.json --project sri-raghavendra-mutt\n`);

  // Check if firebase-admin.json exists for programmatic import
  const adminConfigPath = path.join(process.cwd(), "firebase-admin.json");
  if (fs.existsSync(adminConfigPath)) {
    console.log("✓ Found firebase-admin.json - Admin SDK available");
    console.log("  You can run: npm run generate:aaradhane -- --year " + year + " --firestore");
  } else {
    console.log("✗ firebase-admin.json not found");
    console.log("  To enable automatic import, download service account key:");
    console.log("  Firebase Console > Project Settings > Service accounts > Generate key\n");
  }
}

async function main() {
  const args = process.argv.slice(2);
  let year = new Date().getFullYear() + 1;
  
  const yearIndex = args.indexOf("--year");
  if (yearIndex !== -1 && args[yearIndex + 1]) {
    year = parseInt(args[yearIndex + 1], 10);
  }

  await importEvents(year);
}

main().catch(console.error);
