-- Migration: Seed initial AI settings

INSERT INTO ai_settings (
    id,
    general,
    safety,
    extended_behavior,
    temple_information,
    visitor_information,
    temple_policies,
    ai_responses,
    ai_behavior,
    prompt,
    intents
) VALUES (
    'main',
    '{"enabled": true, "botName": "Raya AI", "botSubtitle": "Official Temple Assistant", "welcomeMessage": "🙏 Namaskara! Welcome to Sri Raghavendra Swamy Matha. How may I help you?", "closingMessage": "🙏 Sri Guru Raghavendraya Namaha! Thank you for visiting.", "defaultLanguage": "en", "supportedLanguages": ["en", "kn", "mixed"]}'::jsonb,
    '{"retrievalRequired": true, "allowLLMOnlyResponse": false, "requireSourceForFacts": true, "unknownQuestionBehaviour": "fallback", "outOfScopeBehaviour": "fallback"}'::jsonb,
    '{"streaming": false, "debugMode": false, "enableAnalytics": true, "enableDebugMode": false, "unknownLogging": true, "semanticThreshold": 0.7, "maxRelatedArticles": 3, "confidenceThreshold": 0.85, "conversationTimeout": 30, "enableFollowUpContext": true, "maxKnowledgeResults": 3, "enableSuggestedQuestions": true, "enableUnknownQuestionLogging": true}'::jsonb,
    '{"contact": {"email": "info@raghavendramatha.org", "phone": "+91-80-28446400", "address": "Sri Raghavendra Swamy Matha, Yelahanka New Town, Bengaluru - 560064, Karnataka, India", "googleMapsUrl": "https://maps.google.com/?q=Sri+Raghavendra+Swamy+Matha+Yelahanka"}, "timings": {"eveningOpen": "5:00 PM", "morningOpen": "6:00 AM", "eveningClose": "8:30 PM", "morningClose": "12:00 PM"}, "officeHours": {"weekday": "9:00 AM - 5:00 PM", "weekend": "10:00 AM - 4:00 PM"}}'::jsonb,
    '{"contact": "Phone: +91-80-28446400, Email: info@raghavendramatha.org", "parking": "Parking is available near the temple premises. Please inquire at the entrance for current parking locations and availability.", "prasada": "Prasada available at counter near exit after darshan.", "annadanam": "Free meals (Annadanam) available at designated hall. Timings: 12:00 PM - 2:00 PM", "dressCode": "Traditional attire preferred. Saree, Kurta, Dhoti recommended.", "guidelines": "Remove footwear before entering. Maintain silence and decorum inside the temple.", "restrooms": "Clean restrooms near entrance and parking area.", "facilities": "Wheelchair access, drinking water, restrooms available.", "testimonials": "Share your spiritual experience at the temple.", "accommodation": "Guest house available. Contact office for booking.", "drinkingWater": "RO water available near entrance and Annadanam hall.", "volunteerInfo": "Contact temple office to join volunteer program.", "wheelchairAccess": "Wheelchair access at main entrance with ramps.", "photographyPolicy": "Photography not allowed inside sanctum. Flash photography prohibited."}'::jsonb,
    '{"donations": "Donations are welcome. Bank transfers, UPI accepted.", "sevaBooking": "Special sevas can be booked online or at temple counter.", "childrenPolicy": "Children welcome. Supervised activities available during festivals.", "information80G": "80G tax exemption available for donations. Contact office for certificate.", "onlineServices": "Online donations, seva booking, and darshan booking available.", "queueGuidelines": "Special queues for senior citizens and differently-abled. General darshan queue available."}'::jsonb,
    '{"welcome": "🙏 Welcome! I''m here to help with temple information, darshan timings, sevas, and more.", "goodbye": "🙏 Sri Guru Raghavendraya Namaha! Thank you for visiting. Please feel free to return anytime!", "fallback": "🙏 Let me provide you with the most relevant information I have.", "greeting": "🙏 Namaskara! Welcome to Sri Raghavendra Swamy Matha. How may I help you?", "outOfScope": "🙏 I''m specifically designed to help with temple-related queries. Please contact the temple office for other topics.", "unknownQuestion": "🙏 I couldn''t find verified information about that. Please contact the temple office for confirmation."}'::jsonb,
    '{"streaming": false, "debugMode": false, "unknownLogging": true, "semanticThreshold": 0.7, "maxRelatedArticles": 3, "confidenceThreshold": 0.85, "conversationTimeout": 30}'::jsonb,
    '{"versions": [{"id": "prompt_v1_seed", "name": "Prompt v1", "status": "published", "content": "You are Raya AI, a helpful virtual assistant for Sri Raghavendra Swamy Matha, Yelahanka.\n\nYour role is to help visitors with:\n- Temple timings and darshan information\n- Seva bookings and procedures\n- Temple history and significance\n- Donation information (including 80G certificates)\n- Facilities available (parking, wheelchair access, etc.)\n- Visitor guidelines and dress code\n- General inquiries about the temple\n\nGuidelines:\n1. Always be respectful and use Namaskara/Sri Guru Raghavendraya Namaha in greetings\n2. Provide accurate information based on available knowledge\n3. If unsure, suggest contacting the temple office: +91-80-28446400\n4. Keep responses concise but informative\n5. Use Kannada (ಕನ್ನಡ) phrases when appropriate for local devotees\n6. For complex queries, offer to connect with temple staff\n\nSri Guru Raghavendraya Namaha! 🙏", "version": 1, "createdAt": "2026-10-12T00:00:00.000Z", "createdBy": "system", "updatedAt": "2026-10-12T00:00:00.000Z"}], "defaultPrompt": "You are Raya AI, a helpful virtual assistant for Sri Raghavendra Swamy Matha, Yelahanka.\n\nYour role is to help visitors with:\n- Temple timings and darshan information\n- Seva bookings and procedures\n- Temple history and significance\n- Donation information (including 80G certificates)\n- Facilities available (parking, wheelchair access, etc.)\n- Visitor guidelines and dress code\n- General inquiries about the temple\n\nGuidelines:\n1. Always be respectful and use Namaskara/Sri Guru Raghavendraya Namaha in greetings\n2. Provide accurate information based on available knowledge\n3. If unsure, suggest contacting the temple office: +91-80-28446400\n4. Keep responses concise but informative\n5. Use Kannada (ಕನ್ನಡ) phrases when appropriate for local devotees\n6. For complex queries, offer to connect with temple staff\n\nSri Guru Raghavendraya Namaha! 🙏", "currentPromptId": "prompt_v1_seed"}'::jsonb,
    '{"intents": [{"id": "INTENT_TIMINGS", "name": "Temple Timings", "status": "enabled", "examples": [{"text": "What are the temple timings?", "language": "en"}], "intentId": "TEMPLE_TIMINGS", "keywords": [{"keyword": "timings", "isActive": true, "language": "en"}, {"keyword": "open", "isActive": true, "language": "en"}, {"keyword": "close", "isActive": true, "language": "en"}], "createdAt": "2026-10-12T00:00:00.000Z", "confidence": 0.8, "usageCount": 0, "description": "Questions about temple opening and closing hours"}, {"id": "INTENT_CONTACT", "name": "Contact Information", "status": "enabled", "examples": [{"text": "How can I contact the temple?", "language": "en"}], "intentId": "CONTACT", "keywords": [{"keyword": "contact", "isActive": true, "language": "en"}, {"keyword": "phone", "isActive": true, "language": "en"}, {"keyword": "call", "isActive": true, "language": "en"}], "createdAt": "2026-10-12T00:00:00.000Z", "confidence": 0.8, "usageCount": 0, "description": "Questions about phone number and email"}, {"id": "INTENT_PARKING", "name": "Parking", "status": "enabled", "examples": [{"text": "Is there parking available?", "language": "en"}], "intentId": "PARKING", "keywords": [{"keyword": "parking", "isActive": true, "language": "en"}, {"keyword": "car", "isActive": true, "language": "en"}], "createdAt": "2026-10-12T00:00:00.000Z", "confidence": 0.8, "usageCount": 0, "description": "Questions about parking facilities"}]}'::jsonb
) ON CONFLICT (id) DO NOTHING;
